apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "{{ .Release.Name }}"
spec:
  action: "ALLOW"
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
    - to:
        - operation:
            methods: ["GET"]
            paths: ["/stats/prometheus"]
  selector:
    matchLabels:
      app.kubernetes.io/name: apiserver
