apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "{{ .Release.Name }}"
spec:
  action: "ALLOW"
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
    - to:
        - operation:
            methods: ["GET"]
            paths: ["/stats/prometheus"]
        - operation:
            methods: ["POST"]
            paths:
              # Allow anonymous searching of public ventures by slug
              - /venture.API/Search
              # Allow anonymous searching of public timelines by venture ID
              - /timeline.API/Search
              # Allow anonymous searching of public timeline updates
              - /update.API/Search
  selector:
    matchLabels:
      app.kubernetes.io/name: apiserver
