apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.apiserver.replica }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}"
    spec:
      containers:
        - name: "{{ .Release.Name }}"
          image: "{{ .Values.image.registry }}/{{ .Values.image.organization }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - daemon
            - --redis-host=rfs-redisfailover.infra.svc.cluster.local
            - --redis-kind=sentinel
            - --redis-port=26379
          ports:
            - name: "grpc"
              containerPort: {{ .Values.apiserver.port }}
      imagePullSecrets:
        - name: "pull-secret"
