apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  jwtRules:
    - issuer: "https://auth.breadcrumb.so/"
      jwksUri: "https://auth.breadcrumb.so/.well-known/jwks.json"
      audiences:
        - "{{ .Release.Name }}"
        - "https://auth.breadcrumb.so/userinfo"
      forwardOriginalToken: true
      fromHeaders:
        - name: "Authorization"
          prefix: "Bearer"
        - name: "Authorization"
          prefix: "bearer"
    - issuer: "public.venturemark.co"
      jwksUri: "https://raw.githubusercontent.com/venturemark/jwks/main/.well-known/keys.json"
      forwardOriginalToken: true
      fromHeaders:
        - name: "Authorization"
          prefix: "Bearer"
        - name: "Authorization"
          prefix: "bearer"
